<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>com.ih.util.session.authorization</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>IH - Session Authorization - Lib</Title>
        <Copyright>Library for Custom Session Management in .NET Rest APIs</Copyright>
        <Company>IH</Company>
        <Authors>Irineu Hübner (irineush@gmail.com)</Authors>
        <Version>1.0.0</Version>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="com-ih-util-cryptography" Version="1.0.0" />
      <PackageReference Include="com-ih-util-custom-errors" Version="1.0.0" />
      <PackageReference Include="com-ih-util-generic" Version="1.0.1" />
    </ItemGroup>
</Project>
