<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>com.ih.session.authorization</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>IH - Session Authorization - Lib</Title>
        <Copyright>Biblioteca privada de IH</Copyright>
        <Company>IH</Company>
        <Authors>Irineu Hübner</Authors>
        <Version>1.0.1</Version>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="IH.Cryptography.Lib" Version="1.1.0" />
      <PackageReference Include="IH.CustomErrors.Util" Version="1.2.0" />
      <PackageReference Include="IH.Generic.Util" Version="1.2.4" />
    </ItemGroup>
</Project>
